#!/usr/bin/env bash
#
# dev-setup.sh - One-command local development setup
#
# This script:
# 1. Verifies Docker is running
# 2. Starts Supabase if not already running
# 3. Detects your local IP address
# 4. Updates .env.local with the correct URLs and dev credentials
# 5. Seeds a dev user in Supabase for password-based login
#
# Usage: npm run dev:setup (from yyx-app directory)
#
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"
SERVER_DIR="$APP_DIR/../yyx-server"
ENV_FILE="$APP_DIR/.env.local"

# Dev user credentials (hardcoded for local dev - not a secret)
DEV_EMAIL="dev@yummyyummix.local"
DEV_PASSWORD="devpassword123"

echo "🍳 YummyYummix Local Dev Setup"
echo "==============================="
echo ""

# Step 1: Check Docker
echo "1️⃣  Checking Docker..."
if ! command -v docker >/dev/null 2>&1; then
  echo -e "${RED}❌ Docker CLI not found. Please install Docker Desktop.${NC}"
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo -e "${RED}❌ Docker daemon not running. Please start Docker Desktop.${NC}"
  exit 1
fi
echo -e "${GREEN}   ✓ Docker is running${NC}"

# Step 2: Check Supabase CLI
echo ""
echo "2️⃣  Checking Supabase CLI..."
if ! command -v supabase >/dev/null 2>&1; then
  echo -e "${RED}❌ Supabase CLI not found. Install with: brew install supabase/tap/supabase${NC}"
  exit 1
fi
echo -e "${GREEN}   ✓ Supabase CLI installed${NC}"

# Step 3: Start Supabase if needed
echo ""
echo "3️⃣  Checking Supabase local stack..."
if ! (cd "$SERVER_DIR" && supabase status >/dev/null 2>&1); then
  echo "   Starting Supabase (this may take a minute)..."
  (cd "$SERVER_DIR" && supabase start)
  echo -e "${GREEN}   ✓ Supabase started${NC}"
else
  echo -e "${GREEN}   ✓ Supabase already running${NC}"
fi

# Step 4: Detect local IP address
echo ""
echo "4️⃣  Detecting local IP address..."
LOCAL_IP=""

# Try en0 (WiFi on most Macs)
if [[ -z "$LOCAL_IP" ]]; then
  LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || true)
fi

# Try en1 (Ethernet or secondary interface)
if [[ -z "$LOCAL_IP" ]]; then
  LOCAL_IP=$(ipconfig getifaddr en1 2>/dev/null || true)
fi

# Fallback: parse routing table
if [[ -z "$LOCAL_IP" ]]; then
  LOCAL_IP=$(route -n get default 2>/dev/null | awk '/interface:/ {iface=$2} END {if(iface) system("ipconfig getifaddr " iface)}' || true)
fi

if [[ -z "$LOCAL_IP" ]]; then
  echo -e "${RED}❌ Could not detect local IP. Make sure you're connected to WiFi.${NC}"
  exit 1
fi
echo -e "${GREEN}   ✓ Local IP: $LOCAL_IP${NC}"

# Step 5: Set Supabase credentials
# These are the well-known demo keys for local Supabase development
# See: https://supabase.com/docs/guides/getting-started/local-development
echo ""
echo "5️⃣  Using local Supabase credentials..."

# Standard local dev keys (HS256 signed, not secrets - safe to hardcode)
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

echo -e "${GREEN}   ✓ Using standard local dev credentials${NC}"

# Step 6: Update .env.local
echo ""
echo "6️⃣  Updating .env.local..."

SUPABASE_URL="http://${LOCAL_IP}:54321"
FUNCTIONS_URL="http://${LOCAL_IP}:54321/functions/v1"

cat > "$ENV_FILE" << EOF
# Local development environment - Auto-generated by dev-setup.sh
# Safe to commit (no secrets, just points to local Supabase)

EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
EXPO_PUBLIC_SUPABASE_FUNCTIONS_URL=${FUNCTIONS_URL}

# Dev login credentials (for the "Dev Login" button on login screen)
EXPO_PUBLIC_DEV_LOGIN_EMAIL=${DEV_EMAIL}
EXPO_PUBLIC_DEV_LOGIN_PASSWORD=${DEV_PASSWORD}
EOF

echo -e "${GREEN}   ✓ Updated .env.local${NC}"

# Step 7: Seed dev user
echo ""
echo "7️⃣  Seeding dev user..."

if ! command -v jq >/dev/null 2>&1; then
  echo -e "${YELLOW}   ⚠ jq not installed. Install with: brew install jq${NC}"
  echo -e "${YELLOW}   Skipping dev user seeding. Create one manually in Supabase Studio.${NC}"
else

SUPABASE_LOCAL_URL="http://127.0.0.1:54321"

# Check if user exists
LIST_RESP=$(curl -s "$SUPABASE_LOCAL_URL/auth/v1/admin/users?per_page=200" \
  -H "apikey: $SERVICE_ROLE_KEY" \
  -H "Authorization: Bearer $SERVICE_ROLE_KEY")

USER_ID=$(echo "$LIST_RESP" | jq -r --arg email "$DEV_EMAIL" '.users[]? | select(.email==$email) | .id' | head -n 1)

if [[ -n "$USER_ID" && "$USER_ID" != "null" ]]; then
  # Update existing user
  UPDATE_RESP=$(curl -s -X PUT "$SUPABASE_LOCAL_URL/auth/v1/admin/users/$USER_ID" \
    -H "apikey: $SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"password\":\"$DEV_PASSWORD\",\"email_confirm\":true}")

  if echo "$UPDATE_RESP" | jq -e '.id' >/dev/null 2>&1; then
    echo -e "${GREEN}   ✓ Updated dev user: $DEV_EMAIL${NC}"
  else
    echo -e "${YELLOW}   ⚠ Could not update dev user. Response: $(echo "$UPDATE_RESP" | jq -c '.')${NC}"
  fi
else
  # Create new user
  CREATE_RESP=$(curl -s -X POST "$SUPABASE_LOCAL_URL/auth/v1/admin/users" \
    -H "apikey: $SERVICE_ROLE_KEY" \
    -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$DEV_EMAIL\",\"password\":\"$DEV_PASSWORD\",\"email_confirm\":true}")

  if echo "$CREATE_RESP" | jq -e '.id' >/dev/null 2>&1; then
    echo -e "${GREEN}   ✓ Created dev user: $DEV_EMAIL${NC}"
  else
    echo -e "${YELLOW}   ⚠ Could not create dev user. Response: $(echo "$CREATE_RESP" | jq -c '.')${NC}"
    echo -e "${YELLOW}   You can create one manually in Supabase Studio: http://localhost:54323${NC}"
  fi
fi

fi  # end jq check

# Done!
echo ""
echo "==============================="
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Run the app:  npm run ios"
echo "  2. On login screen, tap 'Dev Login'"
echo ""
echo "Useful URLs:"
echo "  • Supabase Studio: http://localhost:54323"
echo "  • Inbucket (emails): http://localhost:54324"
echo "  • API:              $SUPABASE_URL"
echo ""
