-- Recipe Embeddings Table
-- Stores vector embeddings for hybrid semantic search (Ability 2)
-- Generated by OpenAI text-embedding-3-large (3072 dimensions)
-- Per irmixy-completion-plan.md Sections 5.1, 5.2
--
-- Note: pgvector extension is in the 'extensions' schema (Supabase default).
-- HNSW max is 2000 dims for vector, 4000 for halfvec — use halfvec cast for index.

create table if not exists public.recipe_embeddings (
  recipe_id uuid primary key references public.recipes(id) on delete cascade,
  embedding extensions.vector(3072) not null,
  embedding_model text not null default 'text-embedding-3-large',
  content_hash text not null,
  updated_at timestamptz not null default now()
);

-- HNSW index using halfvec cast (3072 > 2000 vector limit, within 4000 halfvec limit)
-- Per Supabase docs: https://supabase.com/docs/guides/ai/vector-indexes/hnsw-indexes
create index if not exists idx_recipe_embeddings_embedding
on public.recipe_embeddings
using hnsw ((embedding::extensions.halfvec(3072)) extensions.halfvec_cosine_ops);

-- RLS: service role only (both read and write)
-- App never queries this table directly; all vector searches go through Edge Functions
alter table public.recipe_embeddings enable row level security;

create policy recipe_embeddings_service_only
on public.recipe_embeddings
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

-- RPC function for vector similarity search (used by hybrid-search.ts)
-- PostgREST doesn't support pgvector operators directly, so we wrap in an RPC
create or replace function public.match_recipe_embeddings(
  query_embedding extensions.vector(3072),
  match_threshold float default 0.0,
  match_count int default 50
)
returns table (
  recipe_id uuid,
  similarity float
)
language sql stable
security definer
set search_path = public, extensions
as $$
  select
    re.recipe_id,
    1 - (re.embedding <=> query_embedding) as similarity
  from public.recipe_embeddings re
  where 1 - (re.embedding <=> query_embedding) > match_threshold
  order by re.embedding <=> query_embedding asc
  limit match_count;
$$;

comment on table public.recipe_embeddings is
  'Vector embeddings for hybrid semantic recipe search. Generated by text-embedding-3-large (3072d). Service-role access only.';
