BEGIN;

INSERT INTO recipe_tags (name_en, name_es, categories) VALUES
  ('oil', 'aceite', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('avocadooil', 'aceiteaguacate', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('oliveoil', 'aceiteoliva', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('sides', 'acompañamiento', ARRAY['GENERAL']::recipe_tag_category[]),
  ('african', 'africano', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('avocado', 'aguacate', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('garlic', 'ajo', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('garlicpowder', 'ajoenpolvo', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('basil', 'albahaca', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('almonds', 'almendras', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('cornstarch', 'almidóndemaíz', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('cornstarch', 'maicena', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('kidneybeans', 'alubias', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('cashews', 'anacardos', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('cashews', 'nuezdelaindia', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('new year', 'año nuevo', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('appetizers', 'antojitos', ARRAY['GENERAL']::recipe_tag_category[]),
  ('appetizer', 'aperitivo', ARRAY['GENERAL']::recipe_tag_category[]),
  ('pregnancyfriendly', 'aptoembarazo', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('babyfriendly', 'aptoparabebe', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('rice', 'arroz', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('brownrice', 'arrozintegral', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('asian', 'asiático', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('hazelnuts', 'avellanas', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('oats', 'avena', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('saffron', 'azafrán', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('sugar', 'azúcar', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('darkbrownsugar', 'azúcarmascabado', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('brownsugar', 'azúcarmorena', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('lowcarb', 'bajocarbohidratos', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('lowfat', 'bajoengrasas', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('lowsugar', 'bajosugar', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('banana', 'banana', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('kitchenbasics', 'básicosdelacocina', ARRAY['GENERAL']::recipe_tag_category[]),
  ('pantrybasics', 'básicosdelaalacena', ARRAY['GENERAL']::recipe_tag_category[]),
  ('basics', 'básicos', ARRAY['GENERAL']::recipe_tag_category[]),
  ('drink', 'bebida', ARRAY['GENERAL']::recipe_tag_category[]),
  ('watercress', 'berros', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('bakingsoda', 'bicarbonato de sodio', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('bakingsoda', 'royal', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('snack', 'botana', ARRAY['GENERAL']::recipe_tag_category[]),
  ('brazilian', 'brasileño', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('broccoli', 'brócoli', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('peanuts', 'cacahuates', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('zucchini', 'calabacitas', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('cinnamon', 'canela', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('cantonese', 'cantonés', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('carnival', 'carnaval', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('meat', 'carne', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('homemade', 'casero', ARRAY['GENERAL']::recipe_tag_category[]),
  ('onion', 'cebolla', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('onionpowder', 'cebollaenpolvo', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('dinner', 'cena', ARRAY['GENERAL']::recipe_tag_category[]),
  ('pork', 'cerdo', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('mushrooms', 'champiñones', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('arbolchili', 'chiledearbol', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('guajillopepper', 'chileguajillo', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('moritapepper', 'chilemorita', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('chinese', 'chino', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('cilantro', 'cilantro', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('cloves', 'clavo', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('coconut', 'coco', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('colombian', 'colombiano', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('lunch', 'comida', ARRAY['GENERAL']::recipe_tag_category[]),
  ('comfortfood', 'comidareconfortante', ARRAY['GENERAL']::recipe_tag_category[]),
  ('comfortfood', 'comidadeconsuelo', ARRAY['GENERAL']::recipe_tag_category[]),
  ('cumin', 'comino', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('containssugar', 'contieneazúcar', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containspeanuts', 'contienecacahuates', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsdriedfruits', 'contienefrutossecos', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsgluten', 'contienegluten', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsegg', 'contienehuevo', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsdairy', 'contienelácteos', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsmilk', 'contieneleche', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containshoney', 'contienemiel', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsnuts', 'contienenueces', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containsfish', 'contienepescado', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containschicken', 'contienepollo', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('containstofu', 'contienetofu', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('cream', 'crema', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('couscous', 'cuscús', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('delicious', 'deliciosa', ARRAY['GENERAL']::recipe_tag_category[]),
  ('breakfast', 'desayuno', ARRAY['GENERAL']::recipe_tag_category[]),
  ('fathersday', 'día del padre', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('independenceday', 'díadelaindependencia', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('mothersday', 'díadelasmadres', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('labourday', 'díadeltrabajo', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('dayofthedead', 'díademuertos', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('dip', 'dip', ARRAY['GENERAL']::recipe_tag_category[]),
  ('peach', 'durazno', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('budgetfriendly', 'económico', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('salad', 'ensalada', ARRAY['GENERAL']::recipe_tag_category[]),
  ('starter', 'entrada', ARRAY['GENERAL']::recipe_tag_category[]),
  ('asparagus', 'espárragos', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('spinach', 'espinacas', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('european', 'europeo', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('easy', 'fácil', ARRAY['GENERAL', 'CULTURAL_CUISINE']::recipe_tag_category[]),
  ('family', 'familia', ARRAY['GENERAL']::recipe_tag_category[]),
  ('familiar', 'familiar', ARRAY['GENERAL']::recipe_tag_category[]),
  ('patrioticholidays', 'fiestaspatrias', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('strawberries', 'fresas', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('fresh', 'fresca', ARRAY['GENERAL']::recipe_tag_category[]),
  ('beans', 'frijoles', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('cookies', 'galletas', ARRAY['GENERAL']::recipe_tag_category[]),
  ('chickpeas', 'garbanzos', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('greek', 'griego', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('peas', 'guisantes', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('peas', 'chícharos', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('broadbeans', 'habas', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('halloween', 'halloween', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('flour', 'harina', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('cornmeal', 'harinademaíz', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('ice', 'hielos', ARRAY['INGREDIENTS', 'LIQUID']::recipe_tag_category[]),
  ('oven', 'horno', ARRAY['GENERAL']::recipe_tag_category[]),
  ('eggs', 'huevos', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('indian', 'indio', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('italian', 'italiano', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('ham', 'jamón', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('japanese', 'japonés', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('syrup', 'jarabe', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('agavesyrup', 'jarabeagave', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('ginger', 'jengibre', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('tomato', 'jitomate', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('greenbeans', 'judías', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('juice', 'jugo', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('keto', 'keto', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('kiwi', 'kiwi', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('latinamerican', 'latinoamericano', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('bayleaf', 'laurel', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('milk', 'leche', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('almondmilk', 'lechealmendras', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('oatmilk', 'lecheavena', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('coconutmilk', 'lechecoco', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('sweetenedcondensedmilk', 'lechecondensada', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('lettuce', 'lechuga', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('lentils', 'lentejas', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('lebanese', 'libanés', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('light', 'ligero', ARRAY['GENERAL']::recipe_tag_category[]),
  ('light', 'light', ARRAY['GENERAL', 'CULTURAL_CUISINE']::recipe_tag_category[]),
  ('lemon', 'limón', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('corn', 'maíz', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('mango', 'mango', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('lard', 'manteca', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('shortening', 'mantecavegetal', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('crisco', 'grasavegetal', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('butter', 'mantequilla', ARRAY['INGREDIENTS', 'OILS_AND_FATS', 'DAIRY_AND_ALTERNATIVES']::recipe_tag_category[]),
  ('apple', 'manzana', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('margarine', 'margarina', ARRAY['INGREDIENTS', 'OILS_AND_FATS']::recipe_tag_category[]),
  ('seafood', 'mariscos', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('mediterranean', 'mediterráneo', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('mediterranean', 'comidamediterránea', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('molasses', 'melaza', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('mint', 'menta', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('snack', 'merienda', ARRAY['GENERAL']::recipe_tag_category[]),
  ('mexican', 'mexicano', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('honey', 'miel', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('orange', 'naranja', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('christmas', 'navidad', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('christmaseve', 'nochebuena', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('nuts', 'nueces', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('nuts', 'nuez', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('macadamianuts', 'nuecesdemacadamia', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('macadamianuts', 'macadamia', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('walnuts', 'nuecesdenogal', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('pecans', 'nuecespecanas', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('veganoption', 'opciónvegana', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('oregano', 'oregano', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('oriental', 'oriental', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('paleo', 'paleo', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('bread', 'pan', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('bakery', 'panadería', ARRAY['GENERAL', 'CULTURAL_CUISINE']::recipe_tag_category[]),
  ('easter', 'pascua', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('pasta', 'pasta', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('potatoes', 'patatas', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('turkey', 'pavo', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('cucumber', 'pepino', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('pears', 'peras', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('fish', 'pescado', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('spicy', 'picante', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('paprika', 'pimentón', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('blackpepper', 'pimienta', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('peppers', 'pimientos', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('pineapple', 'piña', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('pistachios', 'pistaches', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('chicken', 'pollo', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('bakingpowder', 'polvoparahornear', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('dessert', 'postre', ARRAY['GENERAL']::recipe_tag_category[]),
  ('cheese', 'queso', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('lactose-freecheese', 'quesosinlactosa', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('quinoa', 'quinoa', ARRAY['GRAINS_AND_STARCHES', 'INGREDIENTS']::recipe_tag_category[]),
  ('quick', 'rápido', ARRAY['GENERAL']::recipe_tag_category[]),
  ('refreshing', 'refrescante', ARRAY['GENERAL']::recipe_tag_category[]),
  ('pastry', 'repostería', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('beef', 'res', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('rosemary', 'romero', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('salt', 'sal', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('savory', 'salado', ARRAY['GENERAL']::recipe_tag_category[]),
  ('healthy', 'saludable', ARRAY['GENERAL']::recipe_tag_category[]),
  ('watermelon', 'sandía', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('holyweek', 'semanasanta', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('corianderseeds', 'semillascilantro', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('chiaseeds', 'semillasdechía', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('sunflowerseeds', 'semillasdegirasol', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('sesameseeds', 'semillasdesesamo', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('sesame', 'ajonjolí', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('pumpkinseeds', 'semillaspipas', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('pumpkinseeds', 'pepitas', ARRAY['INGREDIENTS', 'NUTS_AND_SEEDS']::recipe_tag_category[]),
  ('sugarfree', 'sinazúcar', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('nutfree', 'sinfrutossecos', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('glutenfree', 'singluten', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('lactosefree', 'sinlácteos', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('dairyfree', 'sinmantequilla', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('honeyfree', 'sinmiel', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('soyfree', 'sinsoya', ARRAY['DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('snack', 'snack', ARRAY['GENERAL']::recipe_tag_category[]),
  ('soybeans', 'soja', ARRAY['INGREDIENTS', 'LEGUMES']::recipe_tag_category[]),
  ('stevia', 'stevia', ARRAY['INGREDIENTS', 'SWEETENERS_AND_BAKING']::recipe_tag_category[]),
  ('smooth', 'suave', ARRAY['GENERAL']::recipe_tag_category[]),
  ('thai', 'tailandés', ARRAY['CULTURAL_CUISINE']::recipe_tag_category[]),
  ('tempeh', 'tempeh', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('thanksgiving', 'accióndegracias', ARRAY['GENERAL', 'HOLIDAY']::recipe_tag_category[]),
  ('Thermomix®', 'Thermomix®', ARRAY['GENERAL']::recipe_tag_category[]),
  ('tofu', 'tofu', ARRAY['INGREDIENTS', 'PROTEINS']::recipe_tag_category[]),
  ('tomato', 'tomate', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]),
  ('thyme', 'tomillo', ARRAY['HERBS_AND_SPICES', 'INGREDIENTS']::recipe_tag_category[]),
  ('traditional', 'tradicional', ARRAY['GENERAL', 'CULTURAL_CUISINE']::recipe_tag_category[]),
  ('grapes', 'uvas', ARRAY['FRUITS', 'INGREDIENTS']::recipe_tag_category[]),
  ('vegan', 'vegano', ARRAY['CULTURAL_CUISINE', 'DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('vegetarian', 'vegetariano', ARRAY['CULTURAL_CUISINE', 'DIETARY_RESTRICTIONS']::recipe_tag_category[]),
  ('vinegar', 'vinagre', ARRAY['INGREDIENTS', 'LIQUID']::recipe_tag_category[]),
  ('agua', 'water', ARRAY['INGREDIENTS', 'LIQUID']::recipe_tag_category[]),
  ('vino', 'wine', ARRAY['INGREDIENTS', 'LIQUID']::recipe_tag_category[]),
  ('yogurt', 'yogur', ARRAY['DAIRY_AND_ALTERNATIVES', 'INGREDIENTS']::recipe_tag_category[]),
  ('carrots', 'zanahorias', ARRAY['INGREDIENTS', 'VEGETABLES']::recipe_tag_category[]);

COMMIT;